### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by janosvig** [journeyapps/zxing-android-embedded#479]
When updated from implementation 3.3.2 to 3.4.0. We experienced the following crash.

FATAL EXCEPTION: DecoderThread
Process: com.madeinworld.android.dev, PID: 21482
java.lang.NoSuchMethodError: No interface method sort(Ljava/util/Comparator;)V in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /system/framework/core-libart.jar)
       at com.google.zxing.qrcode.detector.FinderPatternFinder.selectBestPatterns(FinderPatternFinder.java:616)
       at com.google.zxing.qrcode.detector.FinderPatternFinder.find(FinderPatternFinder.java:164)
       at com.google.zxing.qrcode.detector.Detector.detect(Detector.java:81)
       at com.google.zxing.qrcode.QRCodeReader.decode(QRCodeReader.java:77)
       at com.google.zxing.MultiFormatReader.decodeInternal(MultiFormatReader.java:173)
       at com.google.zxing.MultiFormatReader.decodeWithState(MultiFormatReader.java:87)
       at com.journeyapps.barcodescanner.Decoder.decode(Decoder.java:75)
       at com.journeyapps.barcodescanner.Decoder.decode(Decoder.java:49)
       at com.journeyapps.barcodescanner.DecoderThread.decode(DecoderThread.java:146)
       at com.journeyapps.barcodescanner.DecoderThread.access$000(DecoderThread.java:22)
       at com.journeyapps.barcodescanner.DecoderThread$1.handleMessage(DecoderThread.java:38)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:158)
       at android.os.HandlerThread.run(HandlerThread.java:61)

  Android 5.0)**

Actually we were using a Galaxy S5 - Android 6.0.1. And the crash only happens on this device.

**Comment by htchaan** [comment]
with reference to zxing/zxing/pull/1180:
```gradle
    implementation('com.journeyapps:zxing-android-embedded:3.6.0') { transitive = false }
    implementation 'com.google.zxing:core:3.3.3' 
```

**Comment by MykhIvanov** [comment]
@htchaan your solution does not work, still the sort() method is being used in that class

**Comment by rkistner** [comment]
zxing:core 3.4.0 requires a minimum API level of 24 (Android 7.0+). To support older SDK versions you'll need to use an older zxing:core version.
